site_name: Austro Simulator
site_url: https://austrosim.readthedocs.io/

repo_url: https://github.com/wagnerluis1982/AustroSimulator
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - toc.integrate
    - content.action.edit
    - content.action.view
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - css/assembly-ref.css

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true

markdown_extensions:
  - abbr
  - attr_list
  - tables
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.superfences
  - pymdownx.blocks.admonition
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      base_path: [".", "docs"]
      check_paths: true
  - toc:
      permalink: true
