site_name: Austro Simulator

theme:
  name: mkdocs
  highlightjs: true
  color_mode: auto
  user_color_mode_toggle: true
  navigation_depth: 3
  nav_style: dark

extra_css:
  - style/assembly-ref.css

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: 🔗
  - pymdownx.snippets:
      base_path: [".", "docs"]
      check_paths: true
  - pymdownx.caret: {}
  - pymdownx.extra: {}
  - pymdownx.blocks.admonition: {}
